create schema if not exists tabletop;

revoke all on schema tabletop from public;

create table tabletop.players (
    id integer generated by default as identity,
    name character varying(200) not null,
    constraint pk_players primary key (id),
    constraint ck_players_name_not_blank check (btrim(name) <> '')
);

create table tabletop.tournaments (
    id integer generated by default as identity,
    name character varying(200) not null,
    date date not null,
    game_system integer not null,
    constraint pk_tournaments primary key (id),
    constraint ck_tournaments_name_not_blank check (btrim(name) <> ''),
    constraint ck_tournaments_game_system check (game_system between 0 and 3)
);

create table tabletop.tournament_players (
    tournament_id integer not null,
    player_id integer not null,
    constraint pk_tournament_players primary key (tournament_id, player_id),
    constraint fk_tournament_players_tournament
        foreign key (tournament_id)
        references tabletop.tournaments (id)
        on delete cascade,
    constraint fk_tournament_players_player
        foreign key (player_id)
        references tabletop.players (id)
        on delete cascade
);

create index ix_tournament_players_player_id
    on tabletop.tournament_players (player_id);
